### PR TITLE
chore: upgrade prometheus to v1.5.1

### PR DESCRIPTION
**Pull request by alex1989hu**
The current `github.com/prometheus/client_golang` released on Aug 1 2019

Update only to v1.5.1 due to concern of bigger binary
size.

Found the root cause in prometheus v1.6.0 release note:
the package started to include promlint.

Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>

### CODE REVIEW

**Comment by lammel** [comment]
We avoid upgrading the prometheus client to a release above v1.7.1 as it introduces a growth of the binary of about 1MB in most of our projects.

Can you check, if this also impacts your builds?

**Comment by alex1989hu** [comment]
> We avoid upgrading the prometheus client to a release above v1.7.1 as it introduces a growth of the binary of about 1MB in most of our projects.
> 
> Can you check, if this also impacts your builds?

Hmm, interesting. Could you send steps how to measure it, please?

**Comment by alex1989hu** [comment]
cmd/main.go
```go
package main

import (
	"fmt"

	"github.com/labstack/echo-contrib/prometheus"
)

func main() {
	_ = prometheus.Metric{
		MetricCollector: nil,
		ID:              "",
		Name:            "",
		Description:     "",
		Type:            "",
		Args:            nil,
	}
	
	fmt.Println("hello world")
}

```

```bash
go build -o new-prom cmd/main.go
ls -l new-prom
10518564 (<-10M)
git checkout master
go build -o old-prom cmd/main.go
ls -l old-prom
8791732 (<-8.4M)
```

@lammel do you have any tracking issue related to that, or it is just a side-effect of new functionalities, bug fixes etc?

**Comment by lammel** [comment]
Ah, you found out how to test, great.
Thanks for confirming, so upgrading to v1.8+ increases the binary size also more then 1MB.
Moving to v1.7.1 should be OK though, maybe you could try building with that version too, we might upgrade to this version than.

I did not raise an issue yet, as we are mostly moving away from [github.com/prometheus/client_golang](prometheus/client_golang) to [github.com/VictoriaMetrics/metrics](https://github.com/VictoriaMetrics/metrics) which is really lightweight (although more limited).

**Comment by alex1989hu** [comment]
I found that the size:
- is similar either`v1.1.0` or  `v1.5.1` 
- grows to 10M starting with `v1.6.0`
- is similar after `v1.6.0` - does not matter it is `v1.7.1` or `v1.8.0`

**Comment by lammel** [comment]
Ah sorry, my mistake. We are using v1.5.1 not v1.7.1.
That matches with your testing.

I do worry about a >10% growth for the binary, which also needs to be loaded when starting the executable and also causes memory to increase for a usually not required part of the software.

But that should be addressed with the prometheus/client_golang project.

I'm fine with upgrading to v1.5.1 though.

**Comment by alex1989hu** [comment]
> Ah sorry, my mistake. We are using v1.5.1 not v1.7.1.
> That matches with your testing.
> 
> I do worry about a >10% growth for the binary, which also needs to be loaded when starting the executable and also causes memory to increase for a usually not required part of the software.
> 
> But that should be addressed with the prometheus/client_golang project.
> 
> I'm fine with upgrading to v1.5.1 though.

Gotcha, updated both the PR and the commit, too.

**Comment by lammel** [comment]
Did you run `go mod tidy`, there seem to be some dupes in go.sum, but could be due to different version used.
Please check and update PR if required. Will merge then.

**Comment by alex1989hu** [comment]
> Did you run `go mod tidy`, there seem to be some dupes in go.sum, but could be due to different version used.
> Please check and update PR if required. Will merge then.

Sure, i did. Double checked: both in `golang` container and macOS. Also checked the result with the following: removed `go.sum` and  call `go mod tidy` => same change as in the PR.

**Comment by lammel** [comment]
Thanks for your time and contribution @alex1989hu .

**Comment by alex1989hu** [comment]
Your welcome, @lammel PS: if you are able to cut a release, we can start to use it - the latest cut is quite old (March)

**Pull request merged**
