### PR TITLE
Add proper buckets for request/response sizes.

### PR DESCRIPTION
**Pull request by thebaron**
One of the issues I've noticed is that the request size uses the defaults for prom, which are time based, and not size based. This results in files being bucketed on a range from .0005 bytes to 10 bytes in length ... not what we want. This adds some a simplification for file size calculation and the ability to specify the correct bucketing.

    - default buckets in prom are for time, not transfer.
    - adjusts code to create proper bucketing for traffic sizes.

### CODE REVIEW

**Comment by thebaron** [comment]
o/  I see this resulted in a reduction of test coverage by 3/100 of a %. The changes are minor but I tried to come up with a test that might help give us some assurances/confidence that they are being handled correctly. It tests to ensure that the various metrics have the right "unit" bucket and do not have the wrong one. The latter test seems silly, one supposes, but I added it mostly to rule out the possibility of a hungry regex matching on another line's bucket and ensuring it only matches its own le value.
Hopefully this will help with the numbers a bit.

**Comment by thebaron** [comment]
Just wanted to follow up one more time on this PR...

**Comment by aldas** [comment]
Sorry for the delay

**Comment by thebaron** [comment]
No worries, I just wanted
to make sure that I had done everything possible and wasn't missing something or someone was not waiting on me for something! Thanks for the merge!

**Pull request merged**
