### PR TITLE
Support customization of action and object getter

### PR DESCRIPTION
**Pull request by suzaku**
Sometimes the Casbin policies don't match perfectly with the HTTP request paths and methods, this middleware could be more useful if it allows the customization of these two entities.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@appleboy @abingcbc plz review

**Comment by aldas** [comment]
I have created #66 instead of this solution. It will be more generic as it allows to choose enforcers. 

Actions/Methods can be changed before `Enforce` call like that:
```go
ce, _ := casbin.NewEnforcer("auth_model.conf", "auth_policy.csv")
cnf := Config{
	EnforceHandler: func(c echo.Context, user string) (bool, error) {
		method := c.Request().Method
		if strings.HasPrefix(c.Request().URL.Path, "/user/bob") {
			method += "_SELF"
		}
		return ce.Enforce(user, c.Request().URL.Path, method)
	},
}
```

**Comment by suzaku** [comment]
> I have created #66 instead of this solution. It will be more generic as it allows to choose enforcers.
> 
> Actions/Methods can be changed before `Enforce` call like that:
> 
> ```go
> ce, _ := casbin.NewEnforcer("auth_model.conf", "auth_policy.csv")
> cnf := Config{
> 	EnforceHandler: func(c echo.Context, user string) (bool, error) {
> 		method := c.Request().Method
> 		if strings.HasPrefix(c.Request().URL.Path, "/user/bob") {
> 			method += "_SELF"
> 		}
> 		return ce.Enforce(user, c.Request().URL.Path, method)
> 	},
> }
> ```

Cool, very flexible. I have 2 questions though.

1. Will it confuse users if they custom the user getter with a specialize field but have to use `EnforceHandler` for the rest?
2. If I need to write a `EnforceHandler` just to override one field, I might just as well write the whole middleware in my project instead of depending on an external library, right?

**Comment by aldas** [comment]
1. User getter is part of public API and can not be changed/removed.
2. "If I need to write a EnforceHandler just to override one field"  then why create `ActionGetter` at all?

compare `ActionGetter`
```go
		ActionGetter: func(c echo.Context) string {
			method := c.Request().Method
			if strings.HasPrefix(c.Request().URL.Path, "/user/bob") {
				method += "_SELF"
			}
			return method
		},
```

with `EnforceHandler`
```go
		EnforceHandler: func(c echo.Context, user string) (bool, error) {
			method := c.Request().Method
			if strings.HasPrefix(c.Request().URL.Path, "/user/bob") {
				method += "_SELF"
			}
			return ce.Enforce(user, c.Request().URL.Path, method)
		},
```

pretty much the same but latter allows things like #58 need

**Comment by suzaku** [comment]
Yes, the real problem is that this middleware is indeed very simple, so instead of making it customizable, maybe one should just implement it in whatever way suitable in their own project. Thanks for your clarification.

**Pull request closed without merging**
