### PR TITLE
Add Prometheus metrics middleware

### PR DESCRIPTION
**Pull request by carlosedp**
This PR adds a middleware to have Prometheus metrics on Echo application.

### CODE REVIEW

**Comment by carlosedp** [comment]
Hi @vishr can I rebase this for merge?

**Comment by vishr** [comment]
@carlosedp Yes please

**Comment by carlosedp** [comment]
Done! With fixed example import too.

**Comment by vishr** [comment]
@carlosedp thank you. can you also help me updating the website/docs https://github.com/labstack/echox/tree/master/website/content/middleware?

**Comment by carlosedp** [comment]
Sure, I'll take a look next week on adding docs for both middleware.

**Comment by carlosedp** [comment]
Ping @vishr news on merging this? Thanks!

**Comment by vishr** [comment]
@carlosedp Will review it soon

**Comment by carlosedp** [comment]
@vishr done! Also added docs on https://github.com/labstack/echox/pull/111.

**Comment by carlosedp** [comment]
Ping @vishr

**Comment by carlosedp** [comment]
Ping @vishr

**Comment by vishr** [comment]
@carlosedp Thanks for your contribution and sorry about delay!

**Pull request merged**
